###############################################
# Ad Copywriter Agents
# File: agents/agent_04_adcopywriter.py
# Purpose: Defines AI agents for generating Google Ads copy
###############################################

# Import required libraries
from crewai import Agent  # Core CrewAI framework for agents
import streamlit as st  # Streamlit for UI and interactive features

# Class: Ad Copywriter Agents
class AdcopyWriterAgents:
    @staticmethod
    def adcopy_writer_agent():
        """
        Defines the Ad Copy Writer agent responsible for:
        - Creating compelling ad copies for SEM campaigns
        - Crafting headlines and descriptions tailored to SEM strategies
        - Ensuring alignment with business goals, target audience, and keyword plans
        """
        # Create and return the Ad Copy Writer agent
        return Agent(
            role="Lead Ad Copy Writer",  # Define the agent's role
            goal=(
                "Write compelling Google text ads, including headlines and descriptions, tailored to SEM strategies. "
                "Ensure alignment with business goals, target audience, and keyword plans generated by previous agents."
            ),
            backstory=(
                "A creative and strategic ad copywriter with expertise in crafting high-performing Google Ads campaigns. "
                "Proficient in keyword-focused writing and A/B testing for optimization."
            ),
            verbose=True,  # Enable detailed logs for debugging
            memory=True,  # Enable memory to retain context between steps
            guardrails={
                'output_format': 'markdown',  # Ensure output format is Markdown
                'max_retries': 3,  # Maximum retry attempts
                'timeout': 300  # Timeout duration in seconds
            }
        )

# End of file: agents/agent_04_adcopywriter.py
